{
  "$schema": "node_modules/wrangler/config-schema.json",
  "name": "sitemap-crawler-api",
  "main": "dist/index.js",
  "compatibility_date": "2025-03-01",
  "compatibility_flags": [
    "nodejs_compat"
  ],
  "vars": {
    "ENVIRONMENT": "development"
  }
}
